version: '3.3'

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack:latest
    environment:
      - SERVICES=dynamodb
      - LAMBDA_EXECUTOR=docker_reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/tmp/localstack/data

volumes:
  localstack_data:



#version: '2'
#services:
#  dynamodb:
#    image: amazon/dynamodb-local
#    container_name: my-dynamodb
#    hostname: dynamodb
#    restart: always
#    volumes:
#      - ./my-dynamodb-data:/home/dynamodblocal/data
#    ports:
#      - 8000:8000
#    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
#
#
#networks:
#  spring-network:
#    driver: bridge